apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kprompt-coordinator.fullname" . }}
  labels:
    {{- include "kprompt-coordinator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kprompt-coordinator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kprompt-coordinator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kprompt-coordinator.serviceAccountName" . }}
      containers:
        - name: coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - agent
            - coordinator
            - --addr
            - ":{{ .Values.service.port }}"
            {{- if .Values.probe.enabled }}
            - --probe-kube
            - --in-cluster
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
